models/quarto.py
from . import db

class Quarto(db.Model):
    __tablename__ = "quartos"

    id = db.Column(db.Integer, primary_key=True)
    numero = db.Column(db.String(10), nullable=False)
    status = db.Column(db.String(20), default="OK")

    andar_id = db.Column(db.Integer, db.ForeignKey("andares.id"), nullable=False)

    manutencoes = db.relationship(
        "Manutencao",
        backref="quarto",
        lazy=True,
        cascade="all, delete"
    )

routes/quartos.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import db
from models.quarto import Quarto
from models.andar import Andar
from models.manutencao import Manutencao

quartos_bp = Blueprint("quartos", __name__, url_prefix="/quartos")

# # READ
# @quartos_bp.route("/")
# def listar():
#     quartos = Quarto.query.all()
#     return render_template("quartos/list.html", quartos=quartos)


# CREATE
@quartos_bp.route("/novo/<int:andar_id>", methods=["GET", "POST"])
def novo_no_andar(andar_id):
    andar = Andar.query.get_or_404(andar_id)

    if request.method == "POST":
        numero = request.form["numero"]

        quarto = Quarto(
            numero=numero,
            andar_id=andar.id
        )

        db.session.add(quarto)
        db.session.commit()

        return redirect(
            url_for("andares.quartos_do_andar", andar_id=andar.id)
        )

    return render_template(
        "quartos/form.html",
        andar=andar
    )

# UPDATE
@quartos_bp.route("/editar/<int:id>", methods=["GET", "POST"])
def editar(id):
    quarto = Quarto.query.get_or_404(id)
    andar_id = quarto.andar_id  # guarda o contexto

    if request.method == "POST":
        quarto.numero = request.form["numero"]
        db.session.commit()

        return redirect(
            url_for("andares.quartos_do_andar", andar_id=andar_id)
        )

    return render_template(
        "quartos/form.html",
        quarto=quarto,
        andar=quarto.andar
    )


# DELETE
@quartos_bp.route("/excluir/<int:id>")
def excluir(id):
    quarto = Quarto.query.get_or_404(id)
    andar_id = quarto.andar_id  # guarda antes de excluir

    db.session.delete(quarto)
    db.session.commit()

    return redirect(
        url_for("andares.quartos_do_andar", andar_id=andar_id)
    )


#Manutencao
@quartos_bp.route("/<int:quarto_id>/manutencoes")
def manutencoes_do_quarto(quarto_id):
    quarto = Quarto.query.get_or_404(quarto_id)
    manutencoes = Manutencao.query.filter_by(quarto_id=quarto.id).all()

    # Atualiza status automaticamente
    for m in manutencoes:
        m.atualizar_status()

    from models import db
    db.session.commit()

    return render_template(
        "manutencoes/por_quarto.html",
        quarto=quarto,
        manutencoes=manutencoes
    )

templates/quartos/form.html
{% extends "base.html" %}
{% block content %}

<h4>
    {{ "Editar Quarto" if quarto else "Novo Quarto" }}
    {% if andar %} - {{ andar.nome }}{% endif %}
</h4>

<form method="post">
    <div class="mb-3">
        <label>Número do quarto</label>
        <input
            class="form-control"
            name="numero"
            value="{{ quarto.numero if quarto else '' }}"
            required
        >
    </div>

    <button class="btn btn-success">
        {{ "Atualizar" if quarto else "Salvar" }}
    </button>

    {% if andar %}
    <a href="{{ url_for('andares.quartos_do_andar', andar_id=andar.id) }}"
    class="btn btn-secondary">
        Cancelar
    </a>
    {% endif %}

</form>

{% endblock %}

templates/quartos/list.html
{% extends "base.html" %}
{% block content %}

<h4>Quartos do {{ andar.nome }}</h4>

<a href="{{ url_for('quartos.novo_no_andar', andar_id=andar.id) }}"
   class="btn btn-primary mb-3">
    Novo Quarto
</a>

<a href="{{ url_for('andares.listar') }}"
   class="btn btn-secondary mb-3">
    Voltar para Andares
</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Número</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
    {% for quarto in quartos %}
        <tr>
            <td>{{ quarto.numero }}</td>
            <td>{{ quarto.status }}</td>
            <td>
                <a href="{{ url_for('quartos.editar', id=quarto.id) }}"
                   class="btn btn-sm btn-warning">
                    Editar
                </a>
                <a href="{{ url_for('quartos.manutencoes_do_quarto', quarto_id=quarto.id) }}"
                    class="btn btn-sm btn-info">
                        Manutenções
                </a>
                <a href="{{ url_for('quartos.excluir', id=quarto.id) }}"
                   class="btn btn-sm btn-danger"
                   onclick="return confirm('Excluir quarto?')">
                    Excluir
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}